name: portfolio
description: DB Portfolio


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  font_awesome_flutter: ^9.2.0


flutter:

  uses-material-design: true
