name: portfolio
description: DB Portfolio


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  font_awesome_flutter: ^9.2.0
  url_launcher: 6.0.18
  scroll_to_index: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - images/profile_picture.png
    - images/db.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/db.png"

flutter_app_name:
  name: "DB Portfolio"